version: '3'
services:
    app:
        build: .
        ports:
            - 8080:80
        volumes:
            - ./site:/var/www/html
        links:
            - db:postgres

    db:
        image: postgres:12.0 # set version to 9 if you encounter problems.
        volumes:
            - ./docker/postgres/logs:/var/log/postgresql
            - ./docker/postgres/datas:/var/lib/postgresql/data
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        ports:
            - 5432:5432
        environment:
            - POSTGRES_DB=lecuisineur
            - POSTGRES_USER=cuisineur
            - POSTGRES_PASSWORD=cuisineur

            
    phppgadmin:
        image: dockage/phppgadmin
        ports:
            - 8081:80
        environment:
            - PHP_PG_ADMIN_SERVER_DESC=PostgreSQL
            - PHP_PG_ADMIN_SERVER_HOST=db
            - PHP_PG_ADMIN_SERVER_PORT=5432
            - PHP_PG_ADMIN_SERVER_SSL_MODE=allow
        links:
            - db:postgres